### PR TITLE
Ruby 3.2 compatibility

### PR DESCRIPTION
**Pull request by strika**
- Update Bundler and Rake to make them compatible with Ruby 3.2.
- Update code to make it compatible with Ruby 3.2.
- Fix a spec that failed on Ruby 3.2.

### CODE REVIEW

**Comment by strika** [comment]
I see that the build failed on Semaphore Classic, but I don't see any output. Do you?

**Comment by shiroyasha** [comment]
Unfortunately, I also can't see them.

The best move forward would be to migrate to Semaphore 2.0, given that Semaphore Classic is shutting down in the upcoming months. I'll make this transition tomorrow, and ping back on this PR when it is done.

**Comment by shiroyasha** [comment]
@strika I've set up it up Semaphore 2.0. Can you try to rebase with the master branch so we can verify if the updates are working?

**Comment by strika** [comment]
Sure. Done.

**Comment by shiroyasha** [comment]
Awsm, it works. I now also disconnected the commit hook from the Classic to awoid poluting PRs with false build statuses.

Merging this to the master branch. Thank you for updating this gem.

**Comment by strika** [comment]
:+1: Note, this just the first step. I plan the open a couple PRs in the next few days to prepare for the new version that's compatible with newest FactoryBot.

**Pull request merged**
